library(viridis)

# ----- colors & factor levels -----


tissue_colors <- 
  c('abdominal adipose tissue' = '#A7DACD',
    'subcutaneous adipose tissue' = '#A7DACD',
    'adrenal gland' = '#7F6A9C',
    'aorta' = '#A7DACD',
    'cecum' = '#1280C4',
    'bone marrow' = '#A1A8AA',
    'breast' = '#F8BDD7',
    'bronchus' = '#6AA692',
    'bulbourethral gland' = '#95D4F5',
    'ear cartilage' = '#A7DACD',
    'joint cartilage' = '#A7DACD',
    'cervix' = '#F8BDD7',
    'colon' = '#1280C4',
    'duodenum' = '#1280C4',
    'endometrium' = '#F8BDD7',
    'epididymis' = '#95D4F5',
    'esophagus' = '#FBDAD9',
    'fallopian tube' = '#F8BDD7',
    'gallbladder' = '#D1CBE5',
    "Heart muscle" = '#DE6C7D',
    'heart atrium' = '#DE6C7D',
    'heart valva' = '#DE6C7D',
    'heart wall' = '#DE6C7D',
    'ileum' = '#1280C4',
    'jejunum' = '#1280C4',
    'synovial tissue' = '#A7DACD',
    'kidney cortex' = '#F9A266',
    'kidney medulla' = '#F9A266',
    'larynx' = '#6AA692',
    'liver' = '#D1CBE5',
    'lung' = '#6AA692',
    'lymph node' = '#A1A8AA',
    'urethral gland' = '#95D4F5',
    'nasopharynx epithelium' = '#6AA692',
    'olfactory epithelium' = '#6AA692',
    'oral mucosa' = '#FBDAD9',
    'ovary' = '#F8BDD7',
    'pancreas' = '#96C08E',
    'penis' = '#95D4F5',
    'peritoneum' = '#A7DACD',
    'pleura' = '#A7DACD',
    'prostate' = '#95D4F5',
    'rectum' = '#1280C4',
    'salivary gland' = '#FBDAD9',
    'seminal vesicle' = '#95D4F5',
    'skin (groin)' = '#FCCAB3',
    'skin (back)' = '#FCCAB3',
    'lip' = '#FBDAD9',
    'skeletal muscle' = '#DE6C7D',
    'smooth muscle (intestine)' = '#DE6C7D',
    'smooth muscle (uterus)' = '#DE6C7D',
    'spleen' = '#A1A8AA',
    'stomach lower' = '#1280C4',
    'stomach upper' = '#1280C4',
    'tongue' = '#FBDAD9',
    'facial adipose' = '#A7DACD',
    'testis' = '#95D4F5',
    'thymus' = '#A1A8AA',
    'thyroid gland' = '#7F6A9C',
    'tonsil' = '#A1A8AA',
    'trachea' = '#6AA692',
    'urinary bladder' = '#F9A266',
    'vagus nerve' = '#A7DACD',
    'ductus deferens' = '#95D4F5',
    'vein' = '#A7DACD',
    'cingulate cortex' = '#53977F',
    'occipital cortex' = '#53977F',
    'insular cortex' = '#53977F',
    'motor cortex' = '#53977F',
    'prefrontal cortex' = '#53977F',
    'somatosensory cortex' = '#53977F',
    'temporal cortex' = '#53977F',
    'retrosplenial cortex' = '#53977F',
    'olfactory bulb' = '#99D0C1',
    'dorsal hippocampus' = '#B4CE52',
    'ventral hippocampus' = '#B4CE52',
    'entorhinal cortex' = '#B4CE52',
    'subiculum' = '#B4CE52',
    'amygdala' = '#82B579',
    'caudate' = '#53C2EA',
    'putamen' = '#53C2EA',
    'septum' = '#53C2EA',
    'ventral pallidum' = '#53C2EA',
    'thalamus' = '#EA9586',
    'hypothalamus' = '#E6351D',
    'substantia nigra' = '#B67AB3',
    'periaqueductal gray' = '#B67AB3',
    'midbrain' = '#B67AB3',
    'medulla' = '#EA5699',
    'pons' = '#EA5699',
    'cerebellum' = '#FDCA43',
    'corpus callosum' = '#878786',
    'dorsal spinal cord' = '#008BCC',
    'ventral spinal cord' = '#008BCC',
    'superiour colliculi' = '#B67AB3',
    'pituitary gland' = '#7F6A9C',
    'retina' = '#FFEF78',
    'eye' = '#FFEF78',
    'cornea' = '#FFEF78',
    'lens' = '#FFEF78',
    'choroid plexus' = '#A7DACD',
    'dura mater' = '#A7DACD',
    'pineal gland' = '#7F6A9C',
    'parathyroid gland' = '#7F6A9C',
    'placenta' = '#F8BDD7',
    'vagina' = '#F8BDD7',
    'intermediate monocyte' = '#E64B35',
    'non-classical monocyte' = '#E64B35',
    'classical monocyte' = '#E64B35',
    'neutrophil' = '#F39B7F',
    'basophil' = '#F39B7F',
    'eosinophil' = '#F39B7F',
    'T-reg' = '#7D8DAF',
    'MAIT T-cell' = '#7D8DAF',
    'memory CD4 T-cell' = '#7D8DAF',
    'naive CD4 T-cell' = '#7D8DAF',
    'memory CD8 T-cell' = '#7D8DAF',
    'naive CD8 T-cell' = '#7D8DAF',
    'memory B-cell' = '#66287F',
    'naive B-cell' = '#66287F',
    'NK-cell' = '#AD1D78',
    'gdTCR' = '#66287F',
    'myeloid DC' = '#199985',
    'plasmacytoid DC' = '#199985',
    'total PBMC' = '#b30000',
    'cerebral cortex' = '#53977F',
    'olfactory region' = '#99D0C1',
    'hippocampal formation' = '#B4CE52',
    'basal ganglia' = '#53C2EA',
    'pons and medulla' = '#EA5699',
    'spinal cord' = '#008BCC',
    'pitutiary' = '#7F6A9C',
    'monocytes' = '#E64B35',
    'granulocytes' = '#F39B7F',
    'T-cells' = '#7D8DAF',
    'B-cells' = '#66287F',
    'NK-cells' = '#AD1D78',
    'dendritic cells' = '#199985',
    'blood' = '#b30000',
    'adipose tissue' = '#A7DACD',
    'large intestine' = '#1280C4',
    'cartilage' = '#A7DACD',
    'small intestine' = '#1280C4',
    'heart' = '#DE6C7D',
    'kidney' = '#F9A266',
    'upper respiratory system' = '#6AA692',
    'lymphoid tissue' = '#A1A8AA',
    'mouth' = '#FBDAD9',
    'mesothelial tissue' = '#A7DACD',
    'skin' = '#FCCAB3',
    'smooth muscle' = '#DE6C7D',
    'stomach' = '#1280C4',
    'brain' = '#FFDD00',
    'Adipose & soft tissue' = '#A7DACD',
    'Endocrine tissues' = '#7F6A9C',
    'Gastrointestinal tract' = '#1280C4',
    'Bone marrow & immune system' = '#A1A8AA',
    'Breast and female reproductive system' = '#F8BDD7',
    'Respiratory system' = '#6AA693',
    'Male reproductive system' = '#95D4F5',
    'Proximal digestive tract' = '#FBDAD9',
    'Liver & gallbladder' = '#D1CBE5',
    'Muscle tissues' = '#DE6C7D',
    'Kidney & urinary bladder' = '#F9A266',
    'Respiratory system' = '#6AA692',
    'Pancreas' = '#96C08E',
    'Skin' = '#FCCAB3',
    'Brain' = '#FFDD00',
    'Eye' = '#FFEF78',
    'Blood' = '#b30000',
    'Abdominal adipose tissue' = '#A7DACD',
    'Subcutaneous adipose tissue' = '#A7DACD',
    'Adrenal gland' = '#7F6A9C',
    'Aorta' = '#A7DACD',
    'Cecum' = '#1280C4',
    'Bone marrow' = '#A1A8AA',
    'Breast' = '#F8BDD7',
    'Bronchus' = '#6AA692',
    'Bulbourethral gland' = '#95D4F5',
    'Ear cartilage' = '#A7DACD',
    'Joint cartilage' = '#A7DACD',
    'Cervix' = '#F8BDD7',
    'Colon' = '#1280C4',
    'Duodenum' = '#1280C4',
    'Endometrium' = '#F8BDD7',
    'Epididymis' = '#95D4F5',
    'Esophagus' = '#FBDAD9',
    'Fallopian tube' = '#F8BDD7',
    'Gallbladder' = '#D1CBE5',
    'Heart atrium' = '#DE6C7D',
    'Heart valva' = '#DE6C7D',
    'Heart wall' = '#DE6C7D',
    'Ileum' = '#1280C4',
    'Jejunum' = '#1280C4',
    'Synovial tissue' = '#A7DACD',
    'Kidney cortex' = '#F9A266',
    'Kidney medulla' = '#F9A266',
    'Larynx' = '#6AA692',
    'Liver' = '#D1CBE5',
    'Lung' = '#6AA692',
    'Lymph node' = '#A1A8AA',
    'Urethral gland' = '#95D4F5',
    'Nasopharynx epithelium' = '#6AA692',
    'Olfactory epithelium' = '#6AA692',
    'Oral mucosa' = '#FBDAD9',
    'Ovary' = '#F8BDD7',
    'Pancreas' = '#96C08E',
    'Penis' = '#95D4F5',
    'Peritoneum' = '#A7DACD',
    'Pleura' = '#A7DACD',
    'Prostate' = '#95D4F5',
    'Rectum' = '#1280C4',
    'Salivary gland' = '#FBDAD9',
    'Seminal vesicle' = '#95D4F5',
    'Skin (groin)' = '#FCCAB3',
    'Skin (back)' = '#FCCAB3',
    'Lip' = '#FBDAD9',
    'Skeletal muscle' = '#DE6C7D',
    'Smooth muscle (intestine)' = '#DE6C7D',
    'Smooth muscle (uterus)' = '#DE6C7D',
    'Spleen' = '#A1A8AA',
    'Stomach lower' = '#1280C4',
    'Stomach upper' = '#1280C4',
    'Tongue' = '#FBDAD9',
    'Facial adipose' = '#A7DACD',
    'Testis' = '#95D4F5',
    'Thymus' = '#A1A8AA',
    'Thyroid gland' = '#7F6A9C',
    'Tonsil' = '#A1A8AA',
    'Trachea' = '#6AA692',
    'Urinary bladder' = '#F9A266',
    'Vagus nerve' = '#A7DACD',
    'Ductus deferens' = '#95D4F5',
    'Vein' = '#A7DACD',
    'Cingulate cortex' = '#53977F',
    'Occipital cortex' = '#53977F',
    'Insular cortex' = '#53977F',
    'Motor cortex' = '#53977F',
    'Prefrontal cortex' = '#53977F',
    'Somatosensory cortex' = '#53977F',
    'Temporal cortex' = '#53977F',
    'Retrosplenial cortex' = '#53977F',
    'Olfactory bulb' = '#99D0C1',
    'Dorsal hippocampus' = '#B4CE52',
    'Ventral hippocampus' = '#B4CE52',
    'Entorhinal cortex' = '#B4CE52',
    'Subiculum' = '#B4CE52',
    'Amygdala' = '#82B579',
    'Caudate' = '#53C2EA',
    'Putamen' = '#53C2EA',
    'Septum' = '#53C2EA',
    'Ventral pallidum' = '#53C2EA',
    'Thalamus' = '#EA9586',
    'Hypothalamus' = '#E6351D',
    'Substantia nigra' = '#B67AB3',
    'Periaqueductal gray' = '#B67AB3',
    'Midbrain' = '#B67AB3',
    'Medulla' = '#EA5699',
    'Pons' = '#EA5699',
    'Cerebellum' = '#FDCA43',
    'Corpus callosum' = '#878786',
    'Dorsal spinal cord' = '#008BCC',
    'Ventral spinal cord' = '#008BCC',
    'Superiour colliculi' = '#B67AB3',
    'Pituitary gland' = '#7F6A9C',
    'Retina' = '#FFEF78',
    'Cornea' = '#FFEF78',
    'Lens' = '#FFEF78',
    'Choroid plexus' = '#A7DACD',
    'Dura mater' = '#A7DACD',
    'Pineal gland' = '#7F6A9C',
    'Parathyroid gland' = '#7F6A9C',
    'Placenta' = '#F8BDD7',
    'Vagina' = '#F8BDD7',
    'Intermediate monocyte' = '#E64B35',
    'Non-classical monocyte' = '#E64B35',
    'Classical monocyte' = '#E64B35',
    'Neutrophil' = '#F39B7F',
    'Basophil' = '#F39B7F',
    'Eosinophil' = '#F39B7F',
    'T-reg' = '#7D8DAF',
    'MAIT T-cell' = '#7D8DAF',
    'Memory CD4 T-cell' = '#7D8DAF',
    'Naive CD4 T-cell' = '#7D8DAF',
    'Memory CD8 T-cell' = '#7D8DAF',
    'Naive CD8 T-cell' = '#7D8DAF',
    'Memory B-cell' = '#66287F',
    'Naive B-cell' = '#66287F',
    'NK-cell' = '#AD1D78',
    'GdTCR' = '#66287F',
    'Myeloid DC' = '#199985',
    'Plasmacytoid DC' = '#199985',
    'Total PBMC' = '#b30000',
    'Cerebral cortex' = '#53977F',
    'Olfactory region' = '#99D0C1',
    'Hippocampal formation' = '#B4CE52',
    'Basal ganglia' = '#53C2EA',
    'Pons and medulla' = '#EA5699',
    'Spinal cord' = '#008BCC',
    'Pitutiary' = '#7F6A9C',
    'Monocytes' = '#E64B35',
    'Granulocytes' = '#F39B7F',
    'T-cells' = '#7D8DAF',
    'B-cells' = '#66287F',
    'Nk-cells' = '#AD1D78',
    'Dendritic cells' = '#199985',
    'Blood' = '#b30000',
    'Adipose tissue' = '#A7DACD',
    'Large intestine' = '#1280C4',
    'Cartilage' = '#A7DACD',
    'Small intestine' = '#1280C4',
    'Heart' = '#DE6C7D',
    'Kidney' = '#F9A266',
    'Upper respiratory system' = '#6AA692',
    'Lymphoid tissue' = '#A1A8AA',
    'Mouth' = '#FBDAD9',
    'Mesothelial tissue' = '#A7DACD',
    'Skin' = '#FCCAB3',
    'Smooth muscle' = '#DE6C7D',
    'Stomach' = '#1280C4',
    'Brain' = '#FFDD00',
    'Adipose & soft tissue' = '#A7DACD',
    'Endocrine tissues' = '#7F6A9C',
    'Gastrointestinal tract' = '#1280C4',
    'Bone marrow & immune system' = '#A1A8AA',
    'Breast and female reproductive system' = '#F8BDD7',
    'Respiratory system' = '#6AA693',
    'Male reproductive system' = '#95D4F5',
    'Proximal digestive tract' = '#FBDAD9',
    'Liver & gallbladder' = '#D1CBE5',
    'Muscle tissues' = '#DE6C7D',
    'Kidney & urinary bladder' = '#F9A266',
    'Respiratory system' = '#6AA692',
    'Pancreas' = '#96C08E',
    'Skin' = '#FCCAB3',
    'Brain' = '#FFDD00',
    'Eye' = '#FFEF78',
    'Blood' = '#b30000',
    
    'Monocyte' = '#E64B35',
    'Granulocyte' = '#F39B7F',
    'T-cell' = '#7D8DAF',
    'B-cell' = '#66287F',
    'NK-cell' = '#AD1D78',
    'Dendritic cell' = '#199985',
    'T/NK-cell' = "#955593",
    "Unknown" = "gray",
    
    "B/DC" = "#3F6082", 
    "Endothelial" = "brown",
    "Endothelium" = "brown",
    "Monocyte/DC" = "#7F715D", 
    "Epithelium" = "tan1",
    "B/T-cell" = "#715A97",
    "Epithelium/B/T-cell" = "#B87F73",
    "B/T/DC" = "#45798E",
    "Endothelium/DC" = "#5F6157",
    "Trophoblast" = "tan3",
    
    "cervix, uterine" = '#F8BDD7',
    'intestine' = '#1280C4',
    "Not tissue enriched" = "black",
    "heart muscle" = "#DE6C7D",
    "Not enriched" = "darkgray",
    "not enriched" = "darkgray")



  cell_type_palette_old <- 
  c('?' = 'gray',
    'Amacrine' = '#FFDD00',
    'Atrial Cardiomyocyte' = '#DE6C7D',
    "Cardiomyocytes" = '#DE6C7D',
    'B cells' = '#66287F',
    'Basal' = 'tan',
    'Basal cells' = 'tan',
    'Basal epithelia' = 'tan',
    'Bipolar' = '#FFDD00',
    'Cones' = 'orange',
    'Dendritic cells' = '#199985',
    'Endothelial cells' = 'brown',
    'Enterocytes' = 'tan',
    'Epithelial cells' = 'tan',
    'Epithelial cells of prostatic glands' = 'tan',
    "Prostate glands, basal cells" = 'tan',
    "Prostate glands, eptithelial cells" = 'tan',
    'Extravillous trophoblasts' = 'tan',
    'Fibroblastss' = 'tan2',
    'Fibroblasts' = 'tan2',
    'Glomerular parietal Epithelial cells' = 'tan',
    'Goblet' = 'tan',
    'Granulocytes' = '#F39B7F',
    'Hepatocytes' = '#D1CBE5',
    'Hofbauer cells' = '#E64B35',
    'Horizontal' = 'orange',
    'Leydig and myoid-like cells' = '#95D4F5',
    'Luminal 1' = 'brown',
    'Luminal 2' = 'brown',
    'Macrophages' = '#E64B35',
    'Monocytes' = '#E64B35',
    'Muller' = '#FFDD00',
    'Myeloid' = '#E64B35',
    'Myofibroblasts' = 'tan2',
    'NK cells' = '#AD1D78',
    'Paneth cells' = 'tan',
    "Paneth-like cells" = 'tan',
    
    'Progenitor cells' = 'green3',
    'Proximal tubule' = '#F9A266',
    "Renal tubules, distal cells" = '#F9A266',    
    "Renal tubules, proximal cells" = '#F9A266',
    'Retinal ganglion cells' = 'orange',
    'Retinal pigment Epithelial cells' = 'tan',
    'Rods' = 'orange',
    'Sertoli cells' = '#95D4F5',
    'Smooth muscle cells' = '#DE6C7D',
    'Spermatocytes' = '#95D4F5',
    'Spermatogonia' = '#95D4F5',
    "Sperm"= '#95D4F5',
    "Peritubular cells" = '#F9A266',
    "Late spermatids"= '#95D4F5',
    "Spermatids"= '#95D4F5',
    "Early spermatids"= '#95D4F5', 
    'Stellate cells' = '#F9A266',
    'stem cells' = 'darkblue',
    "Stem cells" = 'darkblue',
    "Undifferentiated cells" = "darkblue",
    'Syncytiotrophoblast' = 'tan',
    'T cells' = '#7D8DAF',
    'Transient amplifying cells' = '#1280C4',
    "Transient-amplifying (TA) cells" = '#1280C4',
    
    'Vascular' = 'brown',
    'Ventricular Cardiomyocyte' = '#DE6C7D',
    'Villous cytotrophoblast' = 'tan', 
    'Type II pneumocytes' = 'tan',
    'Type I pneumocytes' = 'tan',
    "Alveolar cells type 1" = 'tan',
    "Alveolar cells type 2" = 'tan',
    " " = "gray",
    "Unknown cell type" = "gray",
    
    
    'Bronchial epithelium, ciliated cells' = 'tan',
    'Bronchial epithelium, mucus-secreting cells' = 'tan',
    "Bronchial epithelium, Club cells" = 'tan',
    "Ciliated cells" = 'tan',
    'Syncytotrophoblasts' = 'tan',
    'acinary' = 'tan',
    'Inflammatory cells' = '#b30000',
    "Immune cells" = '#b30000',
    'Vesicula seminalis' = '#95D4F5',
    'Vesicula seminalis transcripts' = '#95D4F5',
    'Urothelium' = 'tan',
    'Urothelium transcripts' = 'tan',
    'Dendritic cell' = '#199985',
    'Mono' = '#E64B35',
    'Dendritic cell myeloid' = '#199985',
    'Erythrocytes' = '#b30000',
    'Dendritic cell plasmacytoid' = '#199985',
    'Basophils' = '#F39B7F',
    'NK' = '#AD1D78',
    'MAIT' = '#7D8DAF',
    'Neutrophils' = "#F39B7F",
    'Spermatogonia and fibroblasts' = 'blue',
    'Leydig cells and fibroblasts' = 'blue',
    'Leydig cells and myoid cells' = 'blue',
    'Leydig cells and Sertoli cells' = 'blue',
    'Myoid cells' = 'blue',
    'Spermatids and Sertoli cells' = 'blue',
    'Fibroblasts and Leydig cells' = 'blue',
    'Fibroblasts and myoid cells' = 'blue',
    'Spermatogonia and myoid cells' = 'blue',
    'Spermatocytes, spermatids and Sertoli cells' = 'blue',
    'Myoid cells?' = 'blue',
    'Myoid cells and Sertoli cells?' = 'blue',
    'Leydig cells' = 'blue',
    
    'Adipocytes' = '#A7DACD',
    'Cytotrophoblasts' = 'tan',
    'Fibroblasts' = 'tan2',
    'Proximal tubule cells' = '#F9A266',
    'Myoepithelial cells' = '#7F6A9C',
    'Type i pneumocytes' = 'tan',
    'B lymphocytes' = '#66287F',
    'Dendritic cells' = '#199985',
    'T lymphocytes' = '#7D8DAF',
    'Granulocytes' = '#F39B7F',
    'Hofbauer cells' = '#E64B35',
    'Kupffer cells' = '#E64B35',
    "Macrophages (Hofbauer cells)" = '#E64B35',
    "Macrophages (Kupffer cells)" = '#E64B35',
    'Monocytes' = '#E64B35',
    "Erythroid cells" = '#b30000',
    'Erthyroid cells' = '#b30000',
    'Horizontal cells' = 'orange',
    'Natural killer cells' = '#AD1D78',
    'Type ii pneumocytes' = 'tan',
    'Basal epithelial cells of prostatic glands' = 'tan',
    'Decidual cells' = '#F8BDD7',
    'Endothelial cells' = 'peru',
    'Hepatic stellate cells (ito cells)' = '#D1CBE5',
    "Ito cells" = '#D1CBE5',
    'Muller glia cells' = '#FFEF78',
    'Inflammatory cells' = '#b30000',
    'Epithelial cells of prostatic glands' = '#95D4F5',
    'Vesicula seminalis cells' = '#95D4F5',
    'Atrial cardiomyocyte' = '#DE6C7D',
    'Smooth muscle cells' = '#DE6C7D',
    'Ventricular cardiomyocyte' = '#DE6C7D',
    'Urothelial cells' = '#F9A266',
    'Lens' = '#FFEF78',
    'Pigment epithelial cells' = '#FFEF78',
    'Bronchial epithelium, ciliated cells' = 'tan',
    'Bronchial epithelium, mucus-secreting cells' = 'tan',
    'Collecting duct cells' = '#F9A266',
    'Distal tubule cells' = '#F9A266',
    'Syncytotrophoblasts' = '#F8BDD7',
    "Cholangiocytes" = '#D1CBE5',
    'Bipolar cells' = '#FFDD00',
    'Cone photoreceptor cells' = '#FFEF78',
    'Rod photoreceptor cells' = '#FFEF78',
    'Extravillous trophoblasts' = '#F8BDD7',
    
    "Ductal epithelial cells" = "tan",
    "islets of Langerhans" = '#96C08E',
    "Islets of Langerhans" = '#96C08E',
    'Acinar cells' = 'tan',
    "Melanocytes" = "brown",
    "Basal keratinocytes (undifferentiated)" = "tan",
    "Suprabasal keratinocytes (differentiated)" = "tan",
    
    'collecting duct cells' = '#F9A266',
    'distal tubule cells' = '#F9A266',
    'Hepatic stellate cells (Ito cells)' = '#D1CBE5',
    'Hepatic stellate cells' = '#D1CBE5',
    'myoepithelial cells' = '#7F6A9C',
    'proximal tubule cells' = '#F9A266',
    "Goblet cells" = "#1280C4",
    "Goblet cells" = "#1280C4",
    "Mucus-secreting cells" = "#1280C4",
    "luminal epithelial cells" = "tan",
    "luminal epithelial cells" = "tan",
    "neuroendocrine cells" = '#7F6A9C',
    "neuroendocrine cells" = '#7F6A9C',
    "Neuroendocrine cells" = '#7F6A9C',
    "Not annotated" = "gray",
    "Not enriched" = "darkgray",
    "not enriched" = "darkgray",
    "Not cell enriched"= "darkgray")


spec_category_levels <- 
  c('tissue enriched',
    'group enriched', 
    'tissue enhanced', 
    'low tissue specificity',  
    'not detected',
    
    'Tissue enriched',
    'Group enriched', 
    'Tissue enhanced', 
    'Low tissue specificity',  
    'Not detected')

dist_category_levels <- 
  c('detected in all', 
    'detected in many', 
    'detected in some', 
    'detected in single', 
    'not detected',
    
    'Detected in all', 
    'Detected in many', 
    'Detected in some', 
    'Detected in single', 
    'Not detected')

enrichment_overlap_levels <- 
  c("full overlap", 
    "partial overlap", 
    "no overlap",
    
    "Full overlap", 
    "Partial overlap", 
    "No overlap")

shared_category_levels <- 
  c("shared", 
    "minor difference", 
    "medium difference",
    "major difference")

enrichment_overlap_pal <-
  set_names(c(viridis(3), inferno(4),
              viridis(3), inferno(4)),
            c("full overlap", 
              "partial overlap", 
              "no overlap", 
              "shared", 
              "minor difference", 
              "medium difference",
              "major difference",
              
              "Full overlap", 
              "Partial overlap", 
              "No overlap", 
              "Shared", 
              "Minor difference", 
              "Medium difference",
              "Major difference"))


spec_category_overlap_levels <-
  c('tissue enriched full overlap', 
    'tissue enriched partial overlap', 
    'tissue enriched no overlap', 
    'group enriched full overlap',
    'group enriched partial overlap', 
    'group enriched no overlap', 
    'tissue enhanced full overlap',
    'tissue enhanced partial overlap', 
    'tissue enhanced no overlap', 
    'low tissue specificity no overlap', 
    'not detected no overlap')

spec_category_overlap_levels_short <-
  c('tissue enriched FO', 
    'tissue enriched PO', 
    'tissue enriched NO', 
    'group enriched FO',
    'group enriched PO', 
    'group enriched NO', 
    'tissue enhanced FO',
    'tissue enhanced PO', 
    'tissue enhanced NO', 
    'low tissue specificity NO', 
    'not detected NO')

spec_category_overlap_pal <- 
  c('tissue enriched full overlap' = "#E41A1C", 
    'tissue enriched partial overlap' = "#ED6667" , 
    'tissue enriched no overlap' = "#F6B2B3" , 
    'group enriched full overlap' = "#FF9D00",
    'group enriched partial overlap' = "#FFBD55", 
    'group enriched no overlap' = "#FFDEAA", 
    'tissue enhanced full overlap' = "#984EA3",
    'tissue enhanced partial overlap' = "#BA89C1", 
    'tissue enhanced no overlap' = "#DCC3E0", 
    'low tissue specificity no overlap' = "grey40", 
    'not detected no overlap' = "grey")

spec_category_overlap_short_pal <- 
  c('tissue enriched FO' = "#E41A1C", 
    'tissue enriched PO' = "#ED6667" , 
    'tissue enriched NO' = "#F6B2B3" , 
    'group enriched FO' = "#FF9D00",
    'group enriched PO' = "#FFBD55", 
    'group enriched NO' = "#FFDEAA", 
    'tissue enhanced FO' = "#984EA3",
    'tissue enhanced PO' = "#BA89C1", 
    'tissue enhanced NO' = "#DCC3E0", 
    'low tissue specificity NO' = "grey40", 
    'not detected NO' = "grey")


gene_category_pal <- 
  c("tissue enriched" = "#e41a1c",
    "group enriched" = "#FF9D00",
    "tissue enhanced" = "#984ea3",
    "low tissue specificity" = "grey40",
    
    "detected in all" = "#253494",
    "detected in many" = "#2c7fb8",
    "detected in some" = "#41b6c4",
    "detected in single" = "#a1dab4",
    
    "not detected" = "grey", 
    "not detected " = "grey", 
    
    "Tissue enriched" = "#e41a1c",
    "Group enriched" = "#FF9D00",
    "Tissue enhanced" = "#984ea3",
    "Low tissue specificity" = "grey40",
    
    "Detected in all" = "#253494",
    "Detected in many" = "#2c7fb8",
    "Detected in some" = "#41b6c4",
    "Detected in single" = "#a1dab4",
    
    "Not detected" = "grey", 
    "Not detected " = "grey", 
    
    "cluster enriched" = "#e41a1c",
    "cluster enhanced" = "#984ea3",
    "low cluster specificity" = "grey40",
    
    
    "Cluster enriched" = "#e41a1c",
    "Cluster enhanced" = "#984ea3",
    "Low cluster specificity" = "grey40")


gene_category_pal_human_pig <- 
  gene_category_pal %>% 
  enframe() %>% 
  do(bind_rows(mutate(., name = paste(name, "human")),
               mutate(., name = paste(name, "pig")))) %$% 
  set_names(value, name) 

gene_category_pal_comparison <- 
  gene_category_pal %>% 
  enframe() %>% 
  do(bind_rows(mutate(., name = paste(name, "canon")),
               mutate(., name = paste(name, "comparison")))) %$% 
  set_names(value, name) 

anova_pal <- 
  c("Residuals and species" = "gray",
    "Residuals" = "gray", 
    "tissue_ID" = "#D95E37", 
    "comparison_tissue" = "#D95E37", 
    "Tissue" = "#D95E37", 
    "individual" = "#149684", 
    "species" = "#F9C770",
    "Species" = "#F9C770",
    "sex" = "#E8C9C7")

anova_levels <- 
  c("Residuals and species",
    "Residuals", 
    "tissue_ID", 
    "comparison_tissue", 
    "Tissue",
    "individual", 
    "species",
    "Species",
    "sex")

sex_palette <- 
  c("male" = "#D96767", "female" = "#214785")

elevation_identity_levels <- 
  c("identity", "overlapping tissues", "different tissues", "no enrichment")

elevation_identity_pal <- 
  set_names(rev(pals::ocean.haline(9)[c(3, 4, 6, 7)]), elevation_identity_levels)

elevation_overlap_levels <- 
  c("Pig", "Both", "Human")

elevation_overlap_pal <- 
  set_names(rev(pals::ocean.haline(9)[c(3, 4, 6)]), elevation_overlap_levels)

overlap_type_pal <- 
  c("Human" = "#DB1F48",
    "Overlap" = "#004369", 
    "Pig" = "#01949A", 
    "Different tissues" = "orangered")

celltype_pal <- 
  c('B cells' = '#66287F',
    'Cholangiocytes' = 'palegreen4',
    'Endothelial' = 'peru',
    'Erythroid cells' = 'darkred',
    'Hepatic stellate cells' = 'salmon4',
    'Hepatocytes' = 'saddlebrown',
    'Hepatocytes sub' = 'sandybrown',
    'Macrophages' = 'orangered',
    'Plasma cells' = 'slateblue4',
    'T cells' = '#7D8DAF')

celltype_levels <- 
  c('B cells',
    'Plasma cells',
    'T cells',
    'Macrophages',
    'Erythroid cells', 
    'Endothelial', 
    'Cholangiocytes', 
    'Hepatic stellate cells', 
    'Hepatocytes', 
    'Hepatocytes sub')

# protein_type_pal <- 
#   c("secreted" = '#911D51',
#     "membrane" = '#6D4BAA', 
#     "other" = '#008490', 
#     "cd_marker" = '#318F1E', 
#     "transcription_factors" = '#B8801B', 
#     "mitochondrial" = '#E371B4', 
#     "ribosomal" = '#89A0F3', 
#     "none" = "black",
#     '#00C9BC', '#97C542', '#FFA05E')
# 
# protein.localization.palette2 <- c("membrane" = "#CE70A4",
#                                    "secreted" = 	"#FCAC3B",
#                                    "membrane and secreted isoforms" = "#755A85")

# protein.localization.palette <- c("intracellular and membrane isoforms" = "#858141",
#                                   "membrane" = "#6DB9C6",
#                                   "intracellular" = "#FCAC3B",
#                                   "secreted" = 	"#CE70A4",
#                                   "intracellular and secreted isoforms" = "#CF5734",
#                                   "membrane and secreted isoforms" = "#755A85",
#                                   "intracellular, membrane, secreted isoforms" = "#794A39")


cluster_levels <- 
  c("TOTAL", 
    paste0("Cluster-", 0:100))
# ----- themes -----

simple_theme <- 
  theme_bw() + 
  theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())

heatmap_palette = viridis::inferno(20, direction = -1)



theme_stripped <-
  theme(panel.background = element_rect(fill = NA, colour = NA),
        plot.background = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.key = element_rect(colour = NA),
        #legend.position = "bottom",
        #legend.direction = "horizontal",
        legend.key.size= unit(0.3, "cm"),
        legend.title = element_text(face="italic"),
        axis.line = element_line(colour="black",size=0.5))

theme_stripped_frame <-
  theme(panel.background = element_rect(fill = NA, colour = "gray"),
        plot.background = element_rect(fill = NA, color = "gray"),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.key = element_rect(colour = NA),
        #legend.position = "bottom",
        #legend.direction = "horizontal",
        legend.key.size= unit(0.3, "cm"),
        legend.title = element_text(face="italic"),
        axis.line = element_line(colour="black",size=0.5))

theme_angletext <- theme(axis.text.x = element_text(angle = 60, hjust = 1))

# Make plot theme
stripped_theme <-
  theme(panel.background = element_rect(fill = NA, colour = NA),
        plot.background = element_rect(fill = NA, color = NA),
        panel.grid.major = element_blank(),
        panel.grid.minor = element_blank(),
        panel.border = element_blank(),
        legend.key = element_rect(colour = NA),
        #legend.position = "bottom",
        #legend.direction = "horizontal",
        legend.key.size= unit(0.3, "cm"),
        legend.title = element_text(face="italic"),
        axis.line = element_line(colour="black",size=0.5))



# stripped theme facet
stripped_theme_facet <-
  stripped_theme+
  theme(legend.position = "right",
        panel.border = element_rect(color = "gray", fill = NA),
        strip.background = element_rect(fill = "#003253",
                                        color = "#003253"),
        strip.text = element_text(color = "white"))

# stripped theme facet
stripped_theme_HPA <-
  stripped_theme+
  theme(legend.position = "right",
        panel.border = element_rect(color = "gray", fill = NA),
        strip.background = element_rect(fill = "#313131",
                                        color = "#313131"),
        strip.text = element_text(color = "white"), 
        plot.background = element_rect(fill = "#D9D9D9",
                                       color = "#D9D9D9"), 
        panel.background = element_rect(fill = "white",
                                        color = "black"))


